<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RmsSupportHub.Api</AssemblyName>
    <RootNamespace>RmsSupportHub.Api</RootNamespace>
    <UserSecretsId>9440097b-fe3d-4599-843c-7fb12b862d3c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RmsSupportHub.Core\RmsSupportHub.Core.csproj" />
    <ProjectReference Include="..\RmsSupportHub.Data\RmsSupportHub.Data.csproj" />
  </ItemGroup>

</Project>
