<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <RootNamespace>RmsSupportHub.Pos.Desktop.Wpf</RootNamespace>
    <AssemblyName>RmsSupportHub.Pos.Desktop.Wpf</AssemblyName>
    <ApplicationTitle>RMS Support Hub</ApplicationTitle>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RmsSupportHub.Pos.LocalIpc\RmsSupportHub.Pos.LocalIpc.csproj" />
  </ItemGroup>

</Project>
